### ISSUE TITLE
Use of deprecated np.rank function in mpfit/mpfit.py causes warning upon call of gaussfitter.gaussfit

### ISSUE THREAD

**Issue by JulienNGirard** [keflavich/agpy#5]
numpy version: 1.11.1
agpy version: 0.1.3  (from auto conda repository)
conda: 4.2.13

Calling gaussfitter.gaussfit raises a warning due to np.rank L2277 of mpfit.py.
```
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy
/core/fromnumeric.py:2641: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` 
attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
```

Consider replacing all instances of numpy.rank to numpy.ndim to comply with the new numpy standards.
`if numpy.rank(rr) != 2:`
by
`if numpy.ndim(rr) != 2:`
Line 2278 of /Users/jgirard/anaconda/lib/python2.7/site-packages/agpy/mpfit/mpfit.py

**Comment by keflavich** [comment]
Indeed, the agpy version of mpfit is out of date.  I've added a deprecation warning pointing users to 
https://github.com/segasai/astrolibpy/blob/master/mpfit/mpfit.py

**Comment by keflavich** [comment]
Closed by https://github.com/keflavich/agpy/commit/fb3a42d9909b7cd1ba74247530bcc8742f5aaeb1

(but maybe it would be good to copy over the latest mpfit...)
